require("remmian.plugins-setup")

-- Core config
require("remmian.core.options")
require("remmian.core.keymaps")
require("remmian.core.colorscheme")

-- Plugins config
require("remmian.plugins.comment")
require("remmian.plugins.nvim-tree")
require("remmian.plugins.lualine")
require("remmian.plugins.telescope")
require("remmian.plugins.nvim-cmp")
require("remmian.plugins.lsp.mason")
require("remmian.plugins.lsp.lspsaga")
require("remmian.plugins.lsp.lspconfig")
require("remmian.plugins.lsp.null-ls")
require("remmian.plugins.autopairs")
require("remmian.plugins.gitsigns")
require("remmian.plugins.treesitter")
require("remmian.plugins.colorizer")
require("remmian.plugins.lsp.lspkind")
require("remmian.plugins.indent_blankline")
require("remmian.plugins.easymotion")
require("remmian.plugins.toggleterm")
